name: Build

on: [push, pull_request]

jobs:
  build:
    uses: lc-ant/parent/.github/workflows/template.maven-build.yml@develop
  integration-tests:
    needs: build
    uses: lc-ant/parent/.github/workflows/template.maven-integration-tests.yml@develop
    with:
      integration-tests-project-name: lc-ant-service-user-provider
  deploy-snapshot-jars:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    needs: 
      - build
      - integration-tests
    uses: lc-ant/parent/.github/workflows/template.maven-deploy-snapshot-jars.yml@develop
    permissions:
      contents: read
      packages: write
